@Api_HostAddress = http://localhost:5186
@todoId = 2

### Get all todos
GET {{Api_HostAddress}}/todos
Accept: application/json

### Get a specific todo by ID
GET {{Api_HostAddress}}/todos/{{todoId}}
Accept: application/json

### Create a new todo
POST {{Api_HostAddress}}/todos
Content-Type: application/json

{
  "description": "Buy groceries"
}

### Create another todo
POST {{Api_HostAddress}}/todos
Content-Type: application/json

{
  "description": "Finish the project documentation"
}

### Update todo description
PATCH {{Api_HostAddress}}/todos/{{todoId}}
Content-Type: application/json

{
  "description": "Buy groceries and cook dinner"
}

### Mark todo as complete
PATCH {{Api_HostAddress}}/todos/{{todoId}}
Content-Type: application/json

{
  "isCompleted": true
}

### Mark todo as incomplete
PATCH {{Api_HostAddress}}/todos/{{todoId}}
Content-Type: application/json

{
  "isCompleted": false
}

### Update description and mark as complete
PATCH {{Api_HostAddress}}/todos/{{todoId}}
Content-Type: application/json

{
  "description": "Solve world hunger",
  "isCompleted": true
}

### Delete a todo
DELETE {{Api_HostAddress}}/todos/{{todoId}}

###
